# Generated by Django 4.0 on 2021-12-14 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Имя категории товаров')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.IntegerField(null=True, verbose_name='Цена, если у продукта нет никаких модификаторов')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение продукта')),
                ('is_visible', models.BooleanField(default=True, null=True, verbose_name='Видимость продукта')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=100, verbose_name='Имя сайта')),
                ('site_name_browser', models.CharField(default='', max_length=100, verbose_name='Имя сайта для поисковиков')),
                ('main_title', models.TextField(default='', max_length=300, verbose_name='Слоган')),
                ('text_about_delivery', models.TextField(default='', max_length=1000, verbose_name='Текст о стоимости доставки')),
                ('work_start_time', models.TimeField(default=datetime.time(11, 0), verbose_name='Начало работы доставки')),
                ('end_start_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Конец работы доставки')),
                ('self_address_street', models.CharField(default='', max_length=100, verbose_name='Название улицы местоположения')),
                ('self_address_build_number', models.CharField(default='', max_length=15, verbose_name='номер дома местоположения')),
                ('contact_phone', models.CharField(default='', max_length=10, verbose_name='Номер телефона доставки')),
            ],
            options={
                'verbose_name': 'Информация на сайте',
                'verbose_name_plural': 'Информация на сайте',
            },
        ),
        migrations.CreateModel(
            name='ProductModificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя модификатора')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Модификаторы')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Модификаторы',
            },
        ),
    ]
