# Generated by Django 4.0 on 2021-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='static/prod_images', verbose_name='Изображение продукта'),
        ),
    ]
