# Generated by Django 4.0 on 2021-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='contact_phone_full',
            field=models.CharField(default='', max_length=10, verbose_name='Номер телефона доставки, полный'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='contact_phone_viewed',
            field=models.CharField(default='', max_length=10, verbose_name='Номер телефона доставки, видимый'),
        ),
    ]
