# Generated by Django 4.0 on 2021-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_remove_sitedata_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='self_address_build_number',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='self_address_street',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='self_address',
            field=models.CharField(default='', max_length=150, verbose_name='Адрес местоположения'),
        ),
    ]
