# Generated by Django 4.0 on 2021-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена, если у продукта нет никаких модификаторов'),
        ),
        migrations.AlterField(
            model_name='productmodificator',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
    ]
