# Generated by Django 4.0 on 2021-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_remove_productmodificator_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стартовая цена продукта'),
        ),
    ]
