# Generated by Django 3.2.10 on 2022-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0013_auto_20220316_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='min_order',
            field=models.IntegerField(blank=0, default=0, verbose_name='Минимальная сумма заказа.'),
        ),
    ]
